# The base file. docker-compose.yml
services:
  backend:
    container_name: lekidag-backend
    build:
      context: ./project-lekidag-backend # Path to the Dockerfile in backend
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - PORT=5000
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}

  frontend:
    container_name: lekidag-frontend
    build:
      context: ./project-lekidag-frontend # Path to the Dockerfile in frontend
