# Build production image with no dev dependencies
services:
  backend:
    build:
      context: ./project-lekidag-backend
      dockerfile: Dockerfile.production # Use production Dockerfile
    expose:
      - "5000" # Expose for NGINX
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - PORT=5000
      - LOG_LEVEL=${LOG_LEVEL}
      - LOGGER_MORGAN_FORMAT_ADD_REMOTE=${LOGGER_MORGAN_FORMAT_ADD_REMOTE}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    command: node src/server.js # Start the backend manually

  frontend:
    build:
      context: ./project-lekidag-frontend
      dockerfile: Dockerfile.production # Build frontend and serve via NGINX
    expose:
      - "80" # No public port because of NGINX
    depends_on:
      - backend

nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend