# No rebuild needed when updating the src code.
services:
  backend:
    build: ./project-lekidag-backend
    ports:
      - "5000:5000" # The port that backend listen to.
      # Mount local source and config files into the container to enable live code updates without rebuilding.
    volumes:
      - ./project-lekidag-backend/src:/usr/src/app/src
      - ./project-lekidag-backend/test:/usr/src/app/test
      - ./project-lekidag-backend/package.json:/usr/src/app/package.json
      - ./project-lekidag-backend/package-lock.json:/usr/src/app/package-lock.json
    env_file:
      - .env
    command: npm run dev # Run backend server

  frontend:
    build: ./project-lekidag-frontend
    ports:
      - "5173:5173" # Port to Vite.
      # Mount local source and config files into the container to enable live code updates without rebuilding.
    volumes:
      - ./project-lekidag-frontend/src:/usr/src/app/src
      - ./project-lekidag-frontend/package.json:/usr/src/app/package.json
      - ./project-lekidag-frontend/package-lock.json:/usr/src/app/package-lock.json
    command: npm run dev # Run Vite dev server